#
# upstream admin {
#     server admin-1:8080;
# }
#
# upstream user {
#     server backend-1:8080;
#     server backend-2:8080;
# }
#
# upstream payment {
#     server payment-1:8080;
# }
#
# server {
#     server_name user.playground;
#
#     add_header X-Frame-Options         "SAMEORIGIN"                      always;
#     add_header X-Content-Type-Options  "nosniff"                         always;
#     add_header X-XSS-Protection        "1; mode=block"                   always;
#     add_header Referrer-Policy         "strict-origin-when-cross-origin" always;
#     add_header Content-Security-Policy "default-src 'self';"             always;
#
#     listen 80;
#
#     location / {
#         proxy_pass http://user;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Proxy-Host $proxy_host;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }
#
#     location /payment {
#         rewrite ^ / break;
#
#         proxy_pass http://payment;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Proxy-Host $proxy_host;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }
# }
#
# server {
#     server_name admin.playground;
#
#     add_header X-Frame-Options         "SAMEORIGIN"                      always;
#     add_header X-Content-Type-Options  "nosniff"                         always;
#     add_header X-XSS-Protection        "1; mode=block"                   always;
#     add_header Referrer-Policy         "strict-origin-when-cross-origin" always;
#     add_header Content-Security-Policy "default-src 'self';"             always;
#
#     listen 80;
#
#     location / {
#         proxy_pass http://admin;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Proxy-Host $proxy_host;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     }
# }